#ifndef PLAYER_H
#define PLAYER_H

#include <stdint.h>

#include "../xram.h"
#include "npc.h"
#include "../game/game.h"
#include "../object/object.h"

#define PLAYER_SPRITE_SLOT 0U

#define PLAYER_SCREEN_X SCREEN_WIDTH / 2 - HALF_TILE_SIZE
#define PLAYER_SCREEN_Y SCREEN_HEIGHT / 2 - HALF_TILE_SIZE

#define PLAYER_WALK_DOWN_FRAME_0 PLAYER_DIR0_FRAME0
#define PLAYER_WALK_DOWN_FRAME_1 PLAYER_DIR0_FRAME1
#define PLAYER_WALK_DOWN_FRAME_2 PLAYER_DIR0_FRAME0
#define PLAYER_WALK_DOWN_FRAME_3 PLAYER_DIR0_FRAME2
#define PLAYER_ATTACK_DOWN PLAYER_DIR0_ATTACK_FRAME0

#define PLAYER_WALK_LEFT_FRAME_0 PLAYER_DIR1_FRAME0
#define PLAYER_WALK_LEFT_FRAME_1 PLAYER_DIR1_FRAME1
#define PLAYER_WALK_LEFT_FRAME_2 PLAYER_DIR1_FRAME0
#define PLAYER_WALK_LEFT_FRAME_3 PLAYER_DIR1_FRAME2
#define PLAYER_ATTACK_LEFT PLAYER_DIR1_ATTACK_FRAME0

#define PLAYER_WALK_UP_FRAME_0 PLAYER_DIR2_FRAME0
#define PLAYER_WALK_UP_FRAME_1 PLAYER_DIR2_FRAME1
#define PLAYER_WALK_UP_FRAME_2 PLAYER_DIR2_FRAME0
#define PLAYER_WALK_UP_FRAME_3 PLAYER_DIR2_FRAME2
#define PLAYER_ATTACK_UP PLAYER_DIR2_ATTACK_FRAME0

#define PLAYER_WALK_RIGHT_FRAME_0 PLAYER_DIR3_FRAME0
#define PLAYER_WALK_RIGHT_FRAME_1 PLAYER_DIR3_FRAME1
#define PLAYER_WALK_RIGHT_FRAME_2 PLAYER_DIR3_FRAME0
#define PLAYER_WALK_RIGHT_FRAME_3 PLAYER_DIR3_FRAME2
#define PLAYER_ATTACK_RIGHT PLAYER_DIR3_ATTACK_FRAME0


#define DIRECTIONS 4
#define ANIMATION_FRAMES 4

/* Lookup by direction in the row and Animation frame in the column */
static const int PLAYER_DIRTECTION_ANIMATION_LOOKUP[DIRECTIONS][ANIMATION_FRAMES] = {
    { PLAYER_WALK_UP_FRAME_0,  PLAYER_WALK_UP_FRAME_1,  PLAYER_WALK_UP_FRAME_2,  PLAYER_WALK_UP_FRAME_3 },
    { PLAYER_WALK_DOWN_FRAME_0,  PLAYER_WALK_DOWN_FRAME_1,  PLAYER_WALK_DOWN_FRAME_2,  PLAYER_WALK_DOWN_FRAME_3 },
    { PLAYER_WALK_LEFT_FRAME_0,  PLAYER_WALK_LEFT_FRAME_1,  PLAYER_WALK_LEFT_FRAME_2,  PLAYER_WALK_LEFT_FRAME_3},
    { PLAYER_WALK_RIGHT_FRAME_0,  PLAYER_WALK_RIGHT_FRAME_1,  PLAYER_WALK_RIGHT_FRAME_2,  PLAYER_WALK_RIGHT_FRAME_3},
};

typedef struct player_t {
    entity_t entity;
    int16_t screen_org_x;
    int16_t screen_org_y;

    uint8_t key_count;
} player_t;

void player_init(player_t *player);
void player_graphics_init(void);
void player_update(player_t *player, object_t objects[OBJECT_COUNT], npc_t npcs[NPC_COUNT], entity_t monsters[MONSTER_COUNT]);
void player_draw(player_t *player);
void player_damage(player_t *player, uint8_t attack);

#endif // PLAYER_H